const test = [
  {
    id: 1,
    category: "LOGO",
    name: "MOCKUP PROJECT",
    popupName: "IMAGE PROJECT",
    project: "Project : Website",
    clint: "Client : Envato",
    langages: "Langages : HTML, CSS, Javascript",
    preview: "Preview:  ",
    previewLink: " www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-1.jpg",
    popupImg: "https://tunis.ibthemespro.com/img/projects/project-9.jpg",
  },
  {
    id: 2,
    category: "VIDEO",
    name: "Youtube Project",
    popupName: "Youtube Project",
    project: "Project : Video",
    clint: "Client : Videohive",
    langages: "Software : Adobe After Effects",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-2.jpg",
    video:
      "https://www.youtube.com/embed/7e90gBu4pas?enablejsapi=1&version=3&playerapiid=ytplayer",
  },
  {
    id: 3,
    category: "LOGO",
    name: "Slider Project",
    popupName: "Slider Project",
    project: "Project : Website",
    clint: "Client : Themeforest",
    langages: "Langages : HTML, CSS, Javascript",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-3.jpg",
    innerSlider: {
      innerSlider1: "https://tunis.ibthemespro.com/img/projects/project-3.jpg",
      innerSlider2: "https://tunis.ibthemespro.com/img/projects/project-2.jpg",
      innerSlider3: "https://tunis.ibthemespro.com/img/projects/project-1.jpg",
    },
  },
  {
    id: 4,
    category: "VIDEO",
    name: "Local Video Project",
    popupName: "Local Video Project",
    project: "Project : Video",
    clint: "Client : Videohive",
    langages: "Software : Adobe After Effects",
    preview: "Preview :",
    previewLink: "www.envato.com",
    // Software: "Adobe After Effects",
    img: "https://tunis.ibthemespro.com/img/projects/project-4.jpg",
    video: "../public/img/projects/video.mp4",
  },
  {
    id: 5,
    category: "MOCKUP",
    name: " Saas App Project",
    popupName: " Saas App Project",
    project: "Project : Website",
    clint: "Client : Themeforest",
    langages: "HTML, CSS, Javascript",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-5.jpg",
  },
  {
    id: 6,
    category: "MOCKUP",
    name: "MOCKUP PROJECT",
    popupName: "IMAGE PROJECT",
    project: "Project : Website",
    clint: "Client :  Envato",
    langages: "HTML, CSS, Javascript",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-6.jpg",
  },
  {
    id: 7,
    category: "LOGO",
    name: "Facebook Profile",
    popupName: "Facebook Profile",
    project: "Project : Website",
    clint: "Client : Facebook",
    langages: "HTML, CSS, Javascript",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-7.jpg",
  },
  {
    id: 8,
    category: "GRAPHIC_DESIGN",
    name: "Dribbble Profile",
    popupName: "Dribbble Profile",
    project: "Project : Website",
    clint: "Client : Dribbble",
    langages: "HTML, CSS, Javascript",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-8.jpg",
  },
  {
    id: 9,
    category: "GRAPHIC_DESIGN",
    name: " Behance Project",
    popupName: " Behance Project",
    project: "Project : Website",
    clint: "Client : Behance",
    langages: "HTML, CSS, Javascript",
    preview: "Preview :",
    previewLink: "www.envato.com",
    img: "https://tunis.ibthemespro.com/img/projects/project-9.jpg",
  },
];

export default test;
